{
    'name': 'Hospital Management',
    'version': '15.0.1.0.0',
    'category': 'Extra Tools',
    'summary': 'Invoices & Payments',
    'sequence': '0',
    'license': 'AGPL-3',
    'description': "",
    'website': 'https://www.odoo.com/app/invoicing',
    'depends': ['base', 'mail', 'portal', 'sale'],
    'demo': [],
    'data': [
        'views/patient.xml',
        'views/appointment.xml',
        'views/female_patient.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'views/menu.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
